### ISSUE TITLE
Adding Data to Multiple Stores Sequentially

### ISSUE THREAD

**Issue by waynestorrie** [assuncaocharles/ngx-indexed-db#100]
Is it possible to add data to object stores sequentially? I have an issue where I need to add data to different stores, but the data just gets added to the store that was last set and throws an error:

```
Error: Uncaught (in promise): Event: {"isTrusted":true}
```

Here is a [StackBlitz example](https://stackblitz.com/edit/angular-indexed-db-stackoverflow-question?file=src%2Fapp%2Foffline-data.service.ts)

Thanks

**Comment by assuncaocharles** [comment]
Hi @waynefarnworth You can do it, for now the only problem is that you have to explicit switch the current store before use it. I have plans to make it statefull only per component in the future

**Comment by waynestorrie** [comment]
Hi @assuncaocharles Thanks for the reply. Do you have any examples of how I could explicitly switch stores? Hopefully it makes sense what I'm trying to achieve in the [example](https://stackblitz.com/edit/angular-indexed-db-stackoverflow-question?file=src%2Fapp%2Foffline-data.service.ts)

**Comment by assuncaocharles** [comment]
Check the add methods on this example:

https://codesandbox.io/s/angular-09u0j

**Comment by assuncaocharles** [comment]
I am gonna close the issue ( since it doesn't really seem an issue ) but feel free to reopen if I got it wrong.

**Comment by waynestorrie** [comment]
> Check the add methods on this example:
> 
> https://codesandbox.io/s/angular-09u0j

Thanks @assuncaocharles 

I did check this when I found it looking through other issues, which works fine for a click event, but if I wanted to add the data to different stores and just call those functions `OnInit` for example:

```
ngOnInit() {
  /**
  * This will add everything to the animals store
  */
  this.addToPeople();
  this.addToAnimals();
}
```

But I did find that setting a timeout *works*:

```
this.addToPeople();
setTimeout(() => {
  this.addToAnimals();
}, 300);
```

[Here's a fork](https://codesandbox.io/s/angular-9zvz3) of your CodeSandbox with an example of these.

> I am gonna close the issue ( since it doesn't really seem an issue ) but feel free to reopen if I got it wrong.

Maybe this isn't an issue with the package, but is there something we could do to prevent the error and allow for this scenario? I'm happy to do a PR if you have any ideas on the best approach?

**Comment by michaelfdeberry** [comment]
@waynefarnworth In the example your functions are called synchronously, but the storage works asynchronously. 

A better approach would be to return the promise then you can do something like this

```
  async ngOnInit() {
    await this.addToPeople();
    await this.addToAnimals();
  }

  addToPeople() {
    this.dbService.currentStore = "people";
    return this.dbService.add({ name: "Charles", email: "charles" }).then(
      () => {
        console.log("added");
      },
      error => {
        console.log(error);
      }
    );
  }

  addToAnimals() {
    this.dbService.currentStore = "animals";
    return this.dbService.add({ name: "Stark", breed: "labrador" }).then(
      () => {
        console.log("added");
      },
      error => {
        console.log(error);
      }
    );
  }

```

**Comment by waynestorrie** [comment]
Thanks for that @michaelfdeberry, but unfortunately that approach doesn't seem to work either. I did look into async/await but had the same issue, unless I'm missing something else? It would be great if you could update the [CodeSandbox](https://codesandbox.io/s/angular-9zvz3) if you can get this way to work.

**Comment by michaelfdeberry** [comment]
This works for me: https://codesandbox.io/s/angular-e5qpq

However, something I did to avoid managing the store name was to create a very light wrapper around NgxIndexedDBService. It creates a new instance of the service for every store. 

https://github.com/michaelfdeberry/overseer/blob/development/src/OverseerUI/src/app/services/local/indexed-storage.service.ts

**Comment by waynestorrie** [comment]
The issue is I'm doing something like this [(https://codesandbox.io/s/angular-66vy6)](https://codesandbox.io/s/angular-66vy6)

```
async ngOnInit() {
    await this.addToPeople();
    await this.addToAnimals();
  }

  addToPeople() {
    const people = [
      { name: "Charles", email: "charles" },
      { name: "Charles", email: "charles" },
      { name: "Charles", email: "charles" },
      { name: "Charles", email: "charles" },
      { name: "Charles", email: "charles" }
    ];

    this.dbService.currentStore = "people";

    return people.forEach(p => {
      console.log(p);
      this.dbService.add(p);
    });
  }

  addToAnimals() {
    const animals = [
      { name: "Stark", breed: "labrador" },
      { name: "Stark", breed: "labrador" },
      { name: "Stark", breed: "labrador" },
      { name: "Stark", breed: "labrador" },
      { name: "Stark", breed: "labrador" }
    ];

    this.dbService.currentStore = "animals";

    return animals.forEach(a => {
      this.dbService.add(a);
    });
  }
```

This causes the original issue,

Thanks for taking the time with the example and the link for the wrapper, @michaelfdeberry , I'll check that out.

In the meantime if you have any more ideas why this method is failing, it would be appreciated.

**Comment by michaelfdeberry** [comment]
Ok, that's a async issue as well. You will want to use Promise.all to wait until all operations are complete.

I can provide an example when I get home this evening, but it would look something like this https://github.com/michaelfdeberry/overseer/blob/798aafdd9813c55dcd7761ca055e18b09532abbd/src/OverseerUI/src/app/services/local/machines.service.ts#L73

**Comment by waynestorrie** [comment]
@michaelfdeberry Ah I see, it's tricky if you haven't done much with async operations, and finding it hard to find related information around IndexedDB other than basic examples.

> I can provide an example when I get home this evening, but it would look something like this 

I'll take a look at your example just now but a working example would be great if you get the time.

**Comment by michaelfdeberry** [comment]
I updated the CodeSandBox, https://codesandbox.io/s/angular-e5qpq

This will invoke all the add calls and insert the promises into an array. Promise.all will create a single promise that will complete when all promises in the array are completed. 

I moved the setting of the storeName within the iteration as well to ensure that each add call will use the correct store.

**Comment by waynestorrie** [comment]
Perfect - Managed to get my code working as expected now, thanks very much for this.

**Comment by michaelfdeberry** [comment]
I'm glad I could help.

You can add the link

**Comment by assuncaocharles** [comment]
Sorry I didn't have enough time to be helpful here but happy that there are people in the community always ready to help :D
