### ISSUE TITLE
Firefox not working

### ISSUE THREAD

**Issue by saffabook** [assuncaocharles/ngx-indexed-db#103]
I have this all set up nicely, works for chrome and safari, however Firefox doesnt seem to work.

It breaks on 
db.openDatabase

After digging around, the error reported is
**InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.**

[stackoverflow](https://stackoverflow.com/questions/17175741/invalidstateerror-a-mutation-operation-was-attempted-on-a-database-that-did-not)

**Comment by assuncaocharles** [comment]
Hi @saffabook 

Can you try it with the new version 3.0.13 and see if it still?

**Comment by saffabook** [comment]
@assuncaocharles hi there, thanks for the message and I will check this for you as soon as time allows during this festive season.

**Comment by lumoe** [comment]
@saffabook Is it possible, that you use Firefox in private mode? We experienced a similar issue. 
Fact is, that Firefox does not support indexed DB in private mode for security reasons. 
(Please delete if unrelated to issue)

**Comment by saffabook** [comment]
@lumoe ok will set out some time to test this. Sorry got so smashed with work. I will spend an hour on this tomorrow and feedback what I discover. At the mo, for FF I just basically show a blank screen saying offline.

**Comment by saffabook** [comment]
Howdy, I had a look and couldnt get it to work. To be honest an hour was not enough. I will come back to this at one point and post any findings.

**Comment by NiekvR** [comment]
I have the same issue. Works fine for chrome and safari, but throwing an error on firefox:

> Unhandled Promise rejection: IndexedDB error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. ; Zone: <root> ; Task: Promise.then ; Value: IndexedDB error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. 

I'm not using Firefox in private mode, using latest (75.0) and it's only a problem on desktop, mobile works fine

config: 

`const dbConfig: DBConfig  = {
  name: 'kuikenTellerDB',
  version: 1,
  objectStoresMeta: [
    {
      store: 'sightings',
      storeConfig: { keyPath: 'localId', autoIncrement: true },
      storeSchema: [
        { name: 'species', keypath: 'species', options: { unique: false } },
        { name: 'numberOfChicks', keypath: 'numberOfChicks', options: { unique: false } },
        { name: 'gezinEerderGemeld', keypath: 'gezinEerderGemeld', options: { unique: false } },
        { name: 'certaintyRecapture', keypath: 'certaintyRecapture', options: { unique: false } },
        { name: 'habitat', keypath: 'habitat', options: { unique: false } },
        { name: 'remarks', keypath: 'remarks', options: { unique: false } },
        { name: 'lat', keypath: 'lat', options: { unique: false } },
        { name: 'lng', keypath: 'lng', options: { unique: false } },
        { name: 'age', keypath: 'age', options: { unique: false } },
        { name: 'photo', keypath: 'photo', options: { unique: false } },
        { name: 'waarnemingId', keypath: 'waarnemingId', options: { unique: true } },
        { name: 'sigthingDate', keypath: 'sigthingDate', options: { unique: false } },
        { name: 'observerName', keypath: 'observerName', options: { unique: false } },
        { name: 'observerEmail', keypath: 'observerEmail', options: { unique: false } },
        { name: 'permission', keypath: 'permission', options: { unique: false } },
        { name: 'uploaded', keypath: 'uploaded', options: { unique: false } },
        { name: 'gezinEerderGemeldWithId', keypath: 'gezinEerderGemeldWithId', options: { unique: false } },
        { name: 'surface', keypath: 'surface', options: { unique: false } },
        { name: 'shore', keypath: 'shore', options: { unique: false } },
        { name: 'water', keypath: 'water', options: { unique: false } },
        { name: 'numberOfDeaths', keypath: 'numberOfDeaths', options: { unique: false } },
        { name: 'causeOfDeath', keypath: 'causeOfDeath', options: { unique: false } },
        { name: 'deathReason', keypath: 'deathReason', options: { unique: false } },
        { name: 'predation', keypath: 'predation', options: { unique: false } },
        { name: 'aggression', keypath: 'aggression', options: { unique: false } },
        { name: 'humanActivity', keypath: 'humanActivity', options: { unique: false } },
        { name: 'deathReasonOther', keypath: 'deathReasonOther', options: { unique: false } },
        { name: 'extraFeedings', keypath: 'extraFeedings', options: { unique: false } }
      ]
    },
    {
      store: 'preferences',
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [
        { name: 'observerName', keypath: 'observerName', options: { unique: true } },
        { name: 'observerEmail', keypath: 'observerEmail', options: { unique: true } },
        { name: 'permission', keypath: 'permission', options: { unique: false } }
      ]
    }
  ]
};`
