### ISSUE TITLE
Working with multiple stores in new version.

### ISSUE THREAD

**Issue by jahangirabd** [assuncaocharles/ngx-indexed-db#105]
Hi,
We have a multiple stores and one dao service for using indexxed db. On earlier versions (ex. 2.6.1) for getting for ex. fruits we have used getAll('friutsstore') . But for latest version as far as understand we must have ngxindexeddb service which keeps current store name inside service. How we can use with multiple stores on latest versions? Could we create multiple dbservices for every stores?
Thank you.

**Comment by assuncaocharles** [comment]
Hey @jahangirabd 

For now, you have to switch the store in an "ad-hoc" way... I have the intention to improve this in the next versions, but PR's are always welcome... 

You can see an example here: https://codesandbox.io/s/angular-09u0j
