### ISSUE TITLE
Concurrency issue with multiple stores

### ISSUE THREAD

**Issue by alexwiese** [assuncaocharles/ngx-indexed-db#107]
Consider the following code (a real Angular example might be components in different NgZones calling two "data" service methods to get a result).

    this.ngxDatabase.currentStore = "users";
    this.ngxDatabase.getAll()
      .then(users => {
        // do something with users
      });

    this.ngxDatabase.currentStore = "animals";
    this.ngxDatabase.getAll()
      .then(animals => {
        // do something with animals
      });

This creates a race condition because the call to users will return the animals if the `currentStore` is updated before the first operation completes.

I think there is a fundamental issue with having the shared mutable `currentStore` field, as it can be mutated while an operation is still in process.
I think a good (potentially breaking) change would be to pass the "store" to each and every operation as a parameter (rather than storing it as a shared mutable field on the `NgxIndexedDBService`):

    this.ngxDatabase.getAll("users")
      .then(users => {
        // do something with users
      });
    
    this.ngxDatabase.getAll("animals")
      .then(animals => {
        // do something with animals
      });

That way the "store" will be scoped to that operation, and operations won't clobber each other by updating that shared mutable field.

As a workaround for now I am saving the "current operation" promise as a field in my "data" service and am chaining each subsequent operation to it so they are executed sequentially (avoiding the clobbering of the `currentStore`):

    private currentOperation: Promise<any> = Promise.resolve();

    public example() {
      this.execute("users", () => {
        return this.ngxDatabase.getAll();
      }).then(users => {
        // do stuff with users
      });

      this.execute("animals", () => {
        return this.ngxDatabase.getAll();
      }).then(users => {
        // do stuff with animals
      });

    private execute<T>(store: string, callback: () => Promise<T>): Promise<T> {
      return this.currentOperation = this.currentOperation.then(_ => {
        this.ngxDatabase.currentStore = store;
        return callback();
      })
    }
   }

If you are happy with my suggestion I can create a PR with the breaking change, and a new version could be created.
Or we could come up with an additive API that just adds new methods that take in the "store" parameter using the new logic, while leaving the old logic alone for backwards compatibility. Let me know what your thoughts are.

**Comment by bellib** [comment]
@alexwiese thank you

**Comment by assuncaocharles** [comment]
@alexwiese Sorry for the late reply. Yes, it makes sense and actually it was the previous way to do it, my bad this change feel free to open the PR it will be welcomed :D

**Comment by amrtaher1234** [comment]
When will you be able to finish this change ? @alexwiese  and yes it will be a good solution because I rely heavily on calling multiple functions that gets data from indexed DB and that race condition crashes my application.

**Comment by alexwiese** [comment]
> When will you be able to finish this change ? @alexwiese and yes it will be a good solution because I rely heavily on calling multiple functions that gets data from indexed DB and that race condition crashes my application.

PR created
