### ISSUE TITLE
npm does not provide the latest version

### ISSUE THREAD

**Issue by MadAx77** [assuncaocharles/ngx-indexed-db#119]
First of all - Thanks for the great job. I have seen that here is the version which provides the storeName as parameter. But when i install with npm install ngx-indexed-db i allways receive an older version without the storeName parameter.
see also https://www.npmjs.com/package/ngx-indexed-db
Best Axel

**Comment by iseff** [comment]
Second this. Wonder when the next version will be released to npm?

**Comment by jahangirabd** [comment]
Hi, 
Its good send  the store name as  parameter. But still not available on npm.

**Comment by assuncaocharles** [comment]
Hi, sorry for the delay guys...

New version ( 4.0.0 ) released
