### ISSUE TITLE
deleteDatabase taking long time

### ISSUE THREAD

**Issue by Slugsh** [assuncaocharles/ngx-indexed-db#126]
I'm adding thousands of items into IndexedDB. When trying to delete database with deleteDatabase(), returned Promise can take minutes to resolve. I did research about this issue and I think this is because database connections are not closed. And only after browser garbage collection is finished database is deleted.

What do you think, would closing connections after inserting / getting from IndexedDB improve this? Any change of getting it implemented?

**Comment by assuncaocharles** [comment]
In the current implementation, the connections are closed as soon as the DB is used to add or update something.
