### ISSUE TITLE
Example confusion

### ISSUE THREAD

**Issue by grosch** [assuncaocharles/ngx-indexed-db#133]
Your migration example isn't making any sense to me.  You're grabbing the people table, and then adding an index on country and age...neither of which are shown as being columns in the tables.

Also, what's the difference between name and keypath on the storeSchema?  Seems like they're just always the same.

**Comment by assuncaocharles** [comment]
[about the name and the key path](https://stackoverflow.com/questions/32214815/indexeddb-what-is-key-keypath-and-indexname)

About the migration example, it's correct... I am migrating the old table adding something to it in the new DB version.

**Comment by grosch** [comment]
@assuncaocharles Here's my specific confusion.

The current state of the DB is version 3, and it has 'name' and 'email' columns.  The migration shows indexes for country and age.  Neither of those columns exist in the dbconfig shown.

I don't see anything in the migrations saying to remove country and add age as a column, for example.
