### ISSUE TITLE
Data is not getting saved in Microsoft edge browser

### ISSUE THREAD

**Issue by ghost** [assuncaocharles/ngx-indexed-db#143]
Here is my code implemented for saving data into indexed db, but data is not getting saved.
please refer below code and error message.

this.dbService.add('people', obj).then(() => {
     console.log('saved successfully');
}, error => { 
     console.log(error); 
});

![image001](https://user-images.githubusercontent.com/61495744/75747828-f900e980-5d43-11ea-8a6c-4beb88c634a7.jpg)

**Comment by shreekumar551984** [comment]
Even I'm facing the same issue with Edge Browser. A quick turn around will help us.

**Comment by assuncaocharles** [comment]
Related to #139 ?

**Comment by ghost** [comment]
No, Its is not related to #139, While saving we are facing data error. Data is not geting saved in edge browser.

**Comment by coolweb** [comment]
Same for me, it's the same as the put method as #112

**Comment by coolweb** [comment]
I do a pull request for this #147
