### ISSUE TITLE
 Save data to keypath

### ISSUE THREAD

**Issue by bogdanbaghiu** [assuncaocharles/ngx-indexed-db#186]
Hi.

I need to save the date of each day in the keypath.
I have for example 1.000.000 records and each one has its date and time. I group them by date and that array that I have of a date I need to keep it in a row of the indexed db. I have managed to insert the array but with autoincrement = true. But I need it to be false and in the keypath I need to put the date.

Another way I have tried has been to record by record, but it is very slow to enter 1.000.000 records one by one.

There is no possibility to open a transaction and enter the 1.000.000 rows and then close the transaction?

For example in SQL Server, can you do bulk, in indexed db and the angular plugin, can you?

**Comment by assuncaocharles** [comment]
Hi @bogdanbaghiu 

In the current version I don't believe it's possible, but good feat to be added. :)

**Comment by bogdanbaghiu** [comment]
@assuncaocharles 
Thanks for the future update.

Best regards.
