### ISSUE TITLE
createObjectStore not available in 5.0.4?

### ISSUE THREAD

**Issue by saranglakare** [assuncaocharles/ngx-indexed-db#189]
I am getting this error when I try to use `createObjectStore`: 

`Property 'createObjectStore' does not exist on type 'NgxIndexedDBService'`

I am using latest released version (`5.0.4`)

Relevant code:

```
import { NgxIndexedDBService, ObjectStoreMeta } from 'ngx-indexed-db';
...

export class MyClass {

    constructor(private dbService: NgxIndexedDBService) { 
    ...
    this.dbService.createObjectStore(this._storeName, { keyPath: '_id', autoIncrement: false });
    ...
    }
```

Am I doing something wrong?

**Comment by assuncaocharles** [comment]
There's no `createObjectStore` exposed, your stores config should be passed to the `NgxIndexedDBModule.forRoot(dbConfig)`.

See: https://www.npmjs.com/package/ngx-indexed-db#usage

**Comment by saranglakare** [comment]
Thanks for your reply. You are contradicting your documentation though:

![Screen Shot 2020-06-15 at 3 53 04 PM](https://user-images.githubusercontent.com/4996891/84647027-7ed62880-af20-11ea-8aea-b4e097e30156.png)

Also, I can see a PR is merged for allowing dynamic creation of Object stores.

Thanks!

**Comment by assuncaocharles** [comment]
Published in the last version
