### ISSUE TITLE
IE 11 throwing error on getAll

### ISSUE THREAD

**Issue by tonypv** [assuncaocharles/ngx-indexed-db#195]
I am getting an error on IE 11 while using this package. It is working fine on Chrome though. Do I need to add some work around for IE 11 or am I missing something else? 

TypeError: Object doesn't support property or method 'getAll'

Code:  this.dbService.getAll('messages').then(...)

PS: I am not sure if i am supposed to create this as an issue, but after much looking around, I wasn't able to find a solution and didn't find any other way to reach out.

Thanks in advance.

**Comment by assuncaocharles** [comment]
`getAll` doesn't work for IE11

https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/getAll
