### ISSUE TITLE
Can we this with another service file ?

### ISSUE THREAD

**Issue by sujeetjaiswara** [assuncaocharles/ngx-indexed-db#198]
Not able to inject within service file.

**Comment by assuncaocharles** [comment]
Can you provide a sandbox with your problem?

**Comment by sujeetjaiswara** [comment]
I am using something like this sample.
Note: in this sample angular version is 10. so not getting any error.
But, on my project using version 9.0 where i am getting error.

https://stackblitz.com/edit/angular-ivy-df2f6t?file=src/app/app.module.ts

**Comment by assuncaocharles** [comment]
Can you provide an actually repro of the problem? I have here a repro with angular 9 of what you are trying to do but no errors https://codesandbox.io/s/broken-cherry-nb4z6?file=/src/app/app.service.ts
