### ISSUE TITLE
getAllByIndex is Promise or Observable

### ISSUE THREAD

**Issue by matejmihelcic** [assuncaocharles/ngx-indexed-db#202]
Hello,
I found that in documentation (readme.md) writes, that getAllByIndex is Observable, in code is Promise. When I want to execute await this.db.getAllByIndex('sometable', 'someindex', IDBKeyRange.only('somekey')), it doesn't return any data (i try to upgrade from 5.0.5 to 6.0.1)...

**Comment by assuncaocharles** [comment]
Hey @matejmihelcic 

In the version `6` all methods are observables has you can see in the docs :) So for your code work you will need the `.subscribe`

**Comment by matejmihelcic** [comment]
Thank you @assuncaocharles  for your reply, but in source code v 6.0.0 is still promise...

  /**
   * Returns all items by an index.
   * @param storeName The name of the store to query
   * @param indexName The index name to filter
   * @param keyRange  The range value and criteria to apply on the index.
   */
  getAllByIndex(storeName: string, indexName: string, keyRange: IDBKeyRange): Promise<T[]> {
    const data: T[] = [];
    return new Promise<T[]>((resolve, reject) => {
      this.openCursorByIndex(storeName, indexName, keyRange)
        .pipe(take(1))
        .subscribe(
          (event) => {
            const cursor: IDBCursorWithValue = (event.target as IDBRequest<IDBCursorWithValue>).result;
            if (cursor) {
              data.push(cursor.value);
              cursor.continue();
            } else {
              resolve(data);
            }
          },
          (reason) => reject(reason)
        );
    });
  }

**Comment by assuncaocharles** [comment]
Ooooh good catch @matejmihelcic I missed that one, just pushed the code making it a observable, version 6.0.2, it must be published in few minute. 

Thanks for pointing that out 👍
