### ISSUE TITLE
Multi-index keypath support

### ISSUE THREAD

**Issue by Blitzsturm** [assuncaocharles/ngx-indexed-db#211]
Indexed DB supports composite indexes however the metadata doesn't reflect this causing IDE and transpile warnings.  This can be corrected by  adding a string array data type to the keypath in [ngx-indexed-db.meta.ts](https://github.com/assuncaocharles/ngx-indexed-db/blob/master/projects/ngx-indexed-db/src/lib/ngx-indexed-db.meta.ts#L18).  I for example need to query by both latitude and longitude to get results within a specific box-area.

**Existing Interface**
```typescript
export interface ObjectStoreSchema {
    name: string;
    keypath: string; //<<String only
    options: {
        unique: boolean;
        [key: string]: any;
    };
}
```
**Suggested Interface**
```typescript
export interface ObjectStoreSchema {
    name: string;
    keypath: string | string[]; //<<String or array of strings
    options: {
        unique: boolean;
        [key: string]: any;
    };
}
```

In so doing, you can now define a multi-path indexes in the app module.  See the "location" below keypath for example:
```typescript
{
    name: 'geolocation-data',
    version: 1,
    objectStoresMeta: [{
            store: 'globeObjecst',
            storeConfig: { keyPath: 'id', autoIncrement: false },
            storeSchema: [
                { name: 'id', keypath: 'id', options: { unique: true } },
                { name: 'location', keypath: ['location.latitude', 'location.longitude'], options: { unique: false } }
            ]
        }
    ]
}
```

Then the data can be queried with multiple constraints making it faster and easier for something like geolocation:
```typescript
this.dbService.getAllByIndex('globeObjecst', 'location', IDBKeyRange.bound([latMin, lngMin], [latMax, lngMax])).subscribe((globeObjects) => {
  console.log('All: ', globeObjects);
});
```

Fortunately this is a fast/easy fix.

**Comment by GohuApp** [comment]
The second param of method IDBDatabase.createObjectStore(name, options) admits an array of keyPath but storeConfig from ObjectStoreMeta doens't. 

**Existing Interface**

`export interface ObjectStoreMeta {
    store: string;
    storeConfig: {
        keyPath: string;
        autoIncrement: boolean;
        [key: string]: any;
    };
    storeSchema: ObjectStoreSchema[];
}`

**Suggested Interface**

`export interface ObjectStoreMeta {
    store: string;
    storeConfig: {
        keyPath: string | string[];
        autoIncrement: boolean;
        [key: string]: any;
    };
    storeSchema: ObjectStoreSchema[];
}`
