### ISSUE TITLE
getAll is not called after subscription

### ISSUE THREAD

**Issue by jim108dev** [assuncaocharles/ngx-indexed-db#214]
Hi!
The default RxJs behavior is subscribe until `subscriber.complete()` (https://rxjs-dev.firebaseapp.com/guide/observable). `getAll` is not called after the subscription. 

I have made a stackblitz with the regular RxJs behavior and a `getAll` call in comparison:
https://stackblitz.com/edit/angular-indexdb-demo-4yby57?file=src/app/app.component.ts

Maybe I misunderstand, what's the point of `getAll` returning an observable and not a promise? Or how can I change this behavior?
Thanks in advance!

**Comment by assuncaocharles** [comment]
Hi, 

It could make sense to be `Promise`, it is as it was before. The change happened only to make it more conformant with NG code.
