### ISSUE TITLE
Move generic type to methods?

### ISSUE THREAD

**Issue by tunger** [assuncaocharles/ngx-indexed-db#218]
Great library!

I noticed that the generic type is defined on the class.

```typescript
export class NgxIndexedDBService<T = any>
```

However, all methods take the object store name as a parameter. When using the service, I would like to access different object stores. Wouldn't it be better to place the generic type on the methods? e.g.

```typescript
getAll<T>(storeName: string): Observable<T[]>
```

Or am I supposed to use the service differently?

Thanks :)

**Comment by schmkr** [comment]
Also running into this. Would be interesting to know if I'm using it wrong, or that the typings can be changed.

**Comment by assuncaocharles** [comment]
Sounds fair, feel free to open a PR :)
