### ISSUE TITLE
Create object stores dynamically not working 

### ISSUE THREAD

**Issue by Surajathoum** [assuncaocharles/ngx-indexed-db#219]
I tried to create stores dynamically while using application but it didn't worked for me. I had also refer solution to issue number #165 but that also didn't work. 
Can you please check at your end or share any working example.

**Comment by assuncaocharles** [comment]
Can you create and codesandbox repro?

**Comment by Surajathoum** [comment]
> Can you create and codesandbox repro?

Please check below URL and revert if something is missing.

https://codesandbox.io/s/strange-lehmann-0ezb8

**Comment by sidAtHoumm** [comment]
Hi,

facing the same issue. Is there any update on this thread?

**Comment by lunar-safari** [comment]
Me neither. No error thrown, but no new datastore created either.
A fix would be great as this is quite an important function.

**Comment by unusedsymbol** [comment]
```
function CreateObjectStore(indexedDB, dbName, version, storeSchemas, migrationFactory) {
    ...
    request.onupgradeneeded = function (event) {
        const database = event.target.result;
        storeSchemas.forEach((storeSchema) => {
            if (!database.objectStoreNames.contains(storeSchema.store)) {
                const objectStore = database.createObjectStore(storeSchema.store, storeSchema.storeConfig);
```

I think that `request.onupgradeneeded` doesn't get called because the DB version stays the same when creating stores dynamically.

**Comment by assuncaocharles** [comment]
> ```
> function CreateObjectStore(indexedDB, dbName, version, storeSchemas, migrationFactory) {
>     ...
>     request.onupgradeneeded = function (event) {
>         const database = event.target.result;
>         storeSchemas.forEach((storeSchema) => {
>             if (!database.objectStoreNames.contains(storeSchema.store)) {
>                 const objectStore = database.createObjectStore(storeSchema.store, storeSchema.storeConfig);
> ```
> 
> I think that `request.onupgradeneeded` doesn't get called because the DB version stays the same when creating stores dynamically.

Hi @jirifranc 

Please, feel free to open new PR
