### ISSUE TITLE
How to get data without refresh page

### ISSUE THREAD

**Issue by Aliakbari1994** [assuncaocharles/ngx-indexed-db#221]
I add data to the indexed-db. But to get it and display it in the component, I have to refresh the page. Is there a way to get the data without refreshing the page?
How can I refresh only the component that takes the data from the indexed-db?

**Comment by assuncaocharles** [comment]
That looks like you are having more problem with angular than with the lib. Can you quickly repro it in the codesandbox?

**Comment by assuncaocharles** [comment]
Here is a codesandbox adding new objects and not refreshing the page: https://codesandbox.io/s/beautiful-morning-wsqu8?file=/src/app/app.component.ts

Please, feel free to reopen this if it was misunderstood.
