### ISSUE TITLE
Not able to add data to store with Key

### ISSUE THREAD

**Issue by crazyjavatricks** [assuncaocharles/ngx-indexed-db#224]
Hi,

I am getting some error while adding data to the IndexedDB store with passing the key. 
eg: - _this.dbService.add(ApplicationConstants.INDEXED_DB_DATA_STORE, { 'data' :'sampleData'},"sample");_
The  Objectstore is created with **autoIncrement: false**
 
Error on console: 
![image](https://user-images.githubusercontent.com/11722540/101887455-e7961900-3bc2-11eb-8e02-e5530b216146.png)

_Note: Autoincrement key is working_

**Comment by mcarriere** [comment]
I'm experiencing the same issue

**Comment by mcarriere** [comment]
After messing with it a bit more, you can set the keyPath as null and it'll let you use an out-of-line key

      storeConfig: { keyPath: null, autoIncrement: false },

**Comment by andreaslarssen** [comment]
Not anymore, it seems

**Comment by assuncaocharles** [comment]
> Not anymore, it seems

@andreaslarssen what is happening?

**Comment by andreaslarssen** [comment]
The type is defined as string
