### ISSUE TITLE
get not working

### ISSUE THREAD

**Issue by elvysferrari** [assuncaocharles/ngx-indexed-db#23]
return on console: You need to use the openDatabase function to create a database before you query it!

my code;

 public db: any;
  constructor() {
    this.db = new NgxIndexedDB('healthdome', 1);
  }

 openDataBase(version: number, evt?: any) {
    
      this.db.openDatabase(version, evt => {
        let objectPlayerStore = evt.currentTarget.result.createObjectStore('players', { keyPath: 'id', autoIncrement: false });  
        objectPlayerStore.createIndex('person', 'person', { unique: false });
        console.log(objectPlayerStore)
      }, error => { console.log(error)}) 
    
  }

getAll(storeName: string) {
    this.db.getAll(storeName).then(
      obj => {
        return obj;
      },
      error => {
        console.log(error);
      }
    );
  }

on my app.component.
this._ngxIndexedDbService.openDataBase(1);

this._ngxIndexedDbService.getAll("players")

**Comment by assuncaocharles** [comment]
this.db = new NgxIndexedDB('healthdome', 1);
This line is also in your app component?

**Comment by elvysferrari** [comment]
no, in my contructor of service;
in my app component I inject my service 
is the same instance for every app
private _ngxIndexedDbService: NgxIndexedDbService

this._ngxIndexedDbService.getAll("players")

getAll(storeName: string) {
console.log(this.db)   //here it brings the instance correctly
    this.db.getAll(storeName).then(
      obj => {
        return obj;
      },
      error => {
        console.log(error);
      }
    );
  }

in console.log(this,db)

db: IDBDatabase
name: "healthdome"
objectStoreNames: DOMStringList
0: "players"
length: 1
dbName: "healthdome"
dbVersion: 1

but getAll not working

**Comment by elvysferrari** [comment]
so is the error

let db = new NgxIndexedDB('healthdome', 1);
    db.openDatabase(1);
    db.getAll(storeName).then(
      obj => {
        console.log(obj);
      },
      error => {
        console.log(error);
      }
    );

You need to use the openDatabase function to create a database before you query it!

**Comment by assuncaocharles** [comment]
Yes, you are indeed trying to open the database before create it. Just so you can have a better idea, move the creation to inside the constructor of your app.component and you will see it works.

Anyway, can you provide a mini repo with to simulate your problem on stack blitz?

**Comment by elvysferrari** [comment]
You were right, I put it
setTimeout (() => {
       this._ngxIndexedDbService.getAll ("players") / * .then ((ret) => {
         console.log (ret)
       }) * /
       this._ngxIndexedDbService.add ("players", {id: 1, name: "test"})
     }, 5000)

so it's time to create the database, is there any way to check if it's already created?

thank you very much.

**Comment by assuncaocharles** [comment]
You can have a get function in your service that returns a singleton database and get this database in your app component, and then use it.

**Comment by elvysferrari** [comment]
Good idea, thank you one more time.
