### ISSUE TITLE
Multiple Database

### ISSUE THREAD

**Issue by aparzi** [assuncaocharles/ngx-indexed-db#230]
Hi, seeing the code (very readable) and using the library, I noticed that you can interact with only one database. I have readjusted the code with the possibility of using multiple databases. 
Could interest you?

Thanks a lot.

**Comment by JosepAlacid** [comment]
Just upload a PR and you'll be part of: https://github.com/assuncaocharles/ngx-indexed-db/graphs/contributors 
This is a choral project. https://opensource.guide/

**Comment by aparzi** [comment]
@assuncaocharles I have implemented the changes and I would like to do a PR but the 403 error status returns to me. How can I fix it?

![Screenshot from 2021-03-06 16-27-40](https://user-images.githubusercontent.com/16490359/110211916-232a4180-7e99-11eb-97bb-43e9888ab150.png)

Thanks so much

**Comment by assuncaocharles** [comment]
Hi @aparzi  you should push the code to your fork and then open the PR

**Comment by aparzi** [comment]
Hi @assuncaocharles, I cloned the repository, am I wrong?

**Comment by assuncaocharles** [comment]
Yep, you need to fork, clone your fork and work on it

**Comment by aparzi** [comment]
Ok thanks!

**Comment by aparzi** [comment]
Hi @assuncaocharles I've opened a pull request for multiple database support.

Pull request: #231

**Comment by aparzi** [comment]
Hi @assuncaocharles do i have to fix something? Thanks
