### ISSUE TITLE
Support for Angular 11 as peerDependency

### ISSUE THREAD

**Issue by lf-novelt** [assuncaocharles/ngx-indexed-db#233]
Hello,

angular 11 is out for a while now and the package should be able to support it without too much change, It would prevent users facing error messages during `npm install` with angular 11 projects.
![image](https://user-images.githubusercontent.com/46479127/111155031-31ace300-8594-11eb-8e7a-f4094fd54dee.png)

For reference: the angular 11 changelog https://github.com/angular/angular/blob/11.1.x/CHANGELOG.md

Note: angular 12 should be out soon...

**Comment by assuncaocharles** [comment]
Hey @lf-novelt 

Thanks for it, a PR should be very welcomed here :)

**Comment by assuncaocharles** [comment]
Fixed in lastest master.

**Comment by lf-novelt** [comment]
Thanks!
