### ISSUE TITLE
Working with cursor iteration and index

### ISSUE THREAD

**Issue by pascallalonde** [assuncaocharles/ngx-indexed-db#240]
I attempted to work with openCursorByIndex to see if I could manage my own filtering / paging queries.

I have 8000 entries matching the index I am looking for and this query gives them all:

`
    const collection = await this.idbService.getAllByIndex(store, 'division', IDBKeyRange.only(division)).toPromise();
    console.log(collection);
`

I thought I could iterate over a cursor to hopefully get through the data and leave before iterating over all when I have the search result.

This is how I attempted to make it work
`
      const cursorSub = this.idbService.openCursorByIndex(store, 'division', IDBKeyRange.only(division)).subscribe((evt) => {
        console.log(evt);

        if (evt.target) {
          const cursor = (evt.target as IDBOpenDBRequest).result as any;
          if (cursor) {
            console.log(cursor.value);
           // TODO Match the filter before adding to search result
            searchResult.result.push(cursor.value);
            cursor.continue();
          } else {
            const endIndex = new Date().getTime();
            console.log(`Done fetching data in indexeddb. [${endIndex - start}ms]`, store);
            cursorSub.unsubscribe();
            resolve(searchResult);
          }
        } else {
          const endIndex = new Date().getTime();
          console.log(`Done fetching data in indexeddb. [${endIndex - start}ms]`, store);
          cursorSub.unsubscribe();
          resolve(searchResult);
        }
      });
`

But, I guess I don't understand how it should work, but I get only one event and never get called again?
I added the if(evt.target) to see if maybe the event was different on a second call, but it's just never called a 2nd time.

I am using the version 6.1.2 of the library in angular@11.0.9 and chrome@90.0.4430.85

**Comment by assuncaocharles** [comment]
The subscription will happen once and emit the value. I am sorry but I am not sure what you are trying to achieve, can you maybe create a codesandbox reproducing it?

**Comment by pascallalonde** [comment]
Thank you, this confirms I did not understand the feature.
I am looking for a way not to read all 8000 entries if only required 25.

**Comment by assuncaocharles** [comment]
The best way would be to query in a way you get only the needed data

**Comment by pascallalonde** [comment]
Thank you, I'll have to rethink how I can achieve that.
