### ISSUE TITLE
PWA on Ipad-Safari Indexed DB doesn't work

### ISSUE THREAD

**Issue by setbusiness** [assuncaocharles/ngx-indexed-db#254]
Hello,

I have create a PWA with indexedDb stockage in a part of my application (to have offline data) but when i try to use my application on iPad (PWA installed) or Safari browser on iPad indexedb doesn't work. 

My application is with lazy loading module.

**Ipad is iPadOS 14.6**

**Package**
angular:  "^10.1.4"
ngx-indexed-db": "^6.1.2"

Do you have any idea ?

**Comment by assuncaocharles** [comment]
Can you describe the error or any more info? Hard to tell by just what you said.

**Comment by Begolas** [comment]
Hey guys,

we currently have the same issue in our PWA running on iPadOS 14.6. It seems that IdexedDB does not initialize reliably in the Safari browser.
We also tried updating from ngx-indexed-db 6.1.2 to version 9.1.2, unfortunately without success (Angular 11.0.6).
However, the bug has already been communicated to Apple:

[https://bugs.webkit.org/show_bug.cgi?id=226547](https://bugs.webkit.org/show_bug.cgi?id=226547)

**Comment by assuncaocharles** [comment]
Will close this one since it looks like safari issue.
