### ISSUE TITLE
Peer dependencies still set to Angular 10

### ISSUE THREAD

**Issue by mstawick** [assuncaocharles/ngx-indexed-db#256]
Hi,

peer dependencies are still set to Angular 10, which breaks upgrading angular project through ng (without --force option). 
(both v8.0.0 or v9.1.0, seems npm releases are out of sync with GitHub releases).

I don't have experience with Angular libraries, but I believe it's because of this file:
https://github.com/assuncaocharles/ngx-indexed-db/blob/master/projects/ngx-indexed-db/package.json

It causes the issue mentioned here:
https://github.com/assuncaocharles/ngx-indexed-db/issues/246#issuecomment-843684819

**Comment by assuncaocharles** [comment]
Hi, peer dependencies are set for me minimum supported version, I don't think it should be set to the latest.

**Comment by mstawick** [comment]
I can see that you've changed the dependency to a range. I think this should fix ng complaining. Thanks.
