### ISSUE TITLE
Expose validateStoreName to check for existing store

### ISSUE THREAD

**Issue by RepentAndBelieveTheGospel** [assuncaocharles/ngx-indexed-db#261]
I have a situation where I am clearing out a store on logout. The problem I am encountering is when the user clears the browsing cache and then logs out. The clear method of NgxIndexedDBService throws this error:

`ERROR Error: Uncaught (in promise): objectStore does not exists: storeName`

It comes from line 246 in ngx-indexed-db.service.ts -> validateBeforeTransaction(db, storeName, reject);

There needs to be a way to check if the store exists before clearing it out (or any other action where the dev might suspect the store could be missing). I have to do the following in order to avoid this error, which kind of defeats the purpose of using the library:

```
const openDatabase = window.indexedDB.open('DaViS IndexedDB');

        openDatabase.onsuccess = () => {
            const database = openDatabase.result;

            if (database.objectStoreNames.contains('Store name')) {
                this.ngxIndexedDBService.clear('Store name');
            }
        };
```

**Comment by assuncaocharles** [comment]
Hi, 

We expose a method called `validateStoreName` which does exactly what you are saying:

```typescript
export function validateStoreName(db: IDBDatabase, storeName: string): boolean {
  return db.objectStoreNames.contains(storeName);
}
```

But also, we are validating if the DB and the store exists and rejecting the promise if they don't, so what you probably want to do is:

```typescript
    this.db.clear('storename').then().catch(() => { // You got here because either db doesn't exist or you store doesn't exist })
```

Do you have any other suggestion here? @RepentAndBelieveTheGospel

**Comment by aparzi** [comment]
Hi @assuncaocharles,
can you closed this issue or not?

**Comment by RepentAndBelieveTheGospel** [comment]
> Hi,
> 
> We expose a method called `validateStoreName` which does exactly what you are saying:
> 
> ```ts
> export function validateStoreName(db: IDBDatabase, storeName: string): boolean {
>   return db.objectStoreNames.contains(storeName);
> }
> ```
> 
> But also, we are validating if the DB and the store exists and rejecting the promise if they don't, so what you probably want to do is:
> 
> ```ts
>     this.db.clear('storename').then().catch(() => { // You got here because either db doesn't exist or you store doesn't exist })
> ```
> 
> Do you have any other suggestion here? @RepentAndBelieveTheGospel

So sorry for not seeing this way back then. Thank you for taking the time to explain how to do what I've asked. I have no other suggestion now.
