### ISSUE TITLE
addItem returns resolved promise object instead of added item with the autoIncrement key

### ISSUE THREAD

**Issue by CArnaboldi** [assuncaocharles/ngx-indexed-db#263]
Greetings. I'm using ngx-indexed-db with a ng 11 project with the following packages:

```
"dependencies": {
    "@amcharts/amcharts4": "^4.10.17",
    "@angular/animations": "11.1.1",
    "@angular/cdk": "11.1.1",
    "@angular/common": "11.1.1",
    "@angular/compiler": "11.1.1",
    "@angular/core": "11.1.1",
    "@angular/forms": "11.1.1",
    "@angular/platform-browser": "11.1.1",
    "@angular/platform-browser-dynamic": "11.1.1",
    "@angular/router": "11.1.1",
    "@angular/service-worker": "11.1.1",
    "@fortawesome/fontawesome-free": "5.15.1",
    "@microsoft/signalr": "^3.1.6",
    "@ngx-translate/core": "13.0.0",
    "@ngx-translate/http-loader": "6.0.0",
    "@syncfusion/ej2-angular-buttons": "19.1.63",
    "@syncfusion/ej2-angular-calendars": "19.1.64",
    "@syncfusion/ej2-angular-dropdowns": "19.1.64",
    "@syncfusion/ej2-angular-filemanager": "19.1.63",
    "@syncfusion/ej2-angular-grids": "19.1.64",
    "@syncfusion/ej2-angular-inputs": "19.1.63",
    "@syncfusion/ej2-angular-navigations": "19.1.63",
    "@syncfusion/ej2-angular-popups": "19.1.64",
    "@syncfusion/ej2-layouts": "19.1.63",
    "@syncfusion/ej2-locale": "19.1.54",
    "@syncfusion/ej2-notifications": "19.1.63",
    "angular-archwizard": "^6.1.0",
    "angular-gridster2": "^11.0.0",
    "bootstrap": "4.5.3",
    "classlist": "2.0.0",
    "cldr-data": "^36.0.0",
    "intl": "1.2.5",
    "jwt-decode": "^3.1.1",
    "lodash": "4.17.20",
    "modernizr": "3.11.7",
    "ng-dynamic-component": "8.0.1",
    "ngx-bootstrap": "^6.2.0",
    "ngx-extended-pdf-viewer": "8.3.0",
    "ngx-indexed-db": "^9.1.2",
    "ngx-toastr": "^13.2.1",
    "ngx-webcam": "^0.3.0",
    "print-js": "^1.5.0",
    "rxjs": "~6.6.0",
    "screenfull": "5.0.2",
    "simple-line-icons": "2.5.5",
    "source-sans-pro": "3.6.0",
    "spinkit": "2.0.1",
    "tslib": "^2.0.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1101.1",
    "@angular/cli": "11.1.1",
    "@angular/compiler-cli": "11.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }
```

In the context of a store with autoincrement key "Id", with the following setup:

```
      {
        store: veicoliStore,
        storeConfig: { keyPath: 'Id', autoIncrement: true },
        storeSchema: [
          { name: 'VAN', keypath: 'VAN', options: { unique: true } },
          { name: 'Categoria', keypath: 'Categoria', options: { unique: false } },
        ]
      },
```

If I try to do a bulk add (with a single element), everything seems to work fine: the array containing the Id of the single element which was added to the store is correctly returned:

![bulkAdd_1](https://user-images.githubusercontent.com/1839903/124802185-f9248100-df57-11eb-9452-56f22c0b23c9.png)
![bulkAdd_2](https://user-images.githubusercontent.com/1839903/124802179-f88bea80-df57-11eb-91f1-cc3a165a6edc.png)

Instead, if I perform a normal insert, with addItem, according to the API specification, I would expect the item with the autoassigned key to be returned. Instead, what I get back looks completely different:

![addItem_1](https://user-images.githubusercontent.com/1839903/124802190-f9248100-df57-11eb-8340-b8f4ed5dc039.png)
![addItem_2](https://user-images.githubusercontent.com/1839903/124802188-f9248100-df57-11eb-9eaf-ea94479a9c69.png)

Why is that so? Am I missing something?

Thank you

**Comment by CArnaboldi** [comment]
is there any update on this issue? Thanks

**Comment by aparzi** [comment]
Hi @Y3kRulez,
for this method (addItem) there is an issue, that will be solved as soon as possible. If you need to insert an element and have the inserted element as a return, I suggest you use (for the moment) the bulkAdd.

**Comment by CArnaboldi** [comment]
> Hi @Y3kRulez,
> for this method (addItem) there is an issue, that will be solved as soon as possible. If you need to insert an element and have the inserted element as a return, I suggest you use (for the moment) the bulkAdd.

Yeah, that's exactly what I'm doing, I've wrote the following wrapper:

```
private _addEntity<T>(storeName: string, entity: T): Observable<T>{
      return this.localDBServ.bulkAdd<T[]>(storeName, [entity])
          .pipe(
              switchMap(result => this.localDBServ.getByKey<T>(storeName, result[0]))
          );
  }
```

Still, I'll update the package as soon as this issue is fixed..

**Comment by aparzi** [comment]
Perfect, as soon as I can I open a PR that fixes the issue.

Thanks.

**Comment by CArnaboldi** [comment]
any update on this? Thanks!
