### ISSUE TITLE
How can I avoid persistent connection to a database to be able to handle more than one tab

### ISSUE THREAD

**Issue by JonasC97** [assuncaocharles/ngx-indexed-db#266]
Hi, 
first of all: thanks for providing your IDB service! 

I am having a general IDB problem. I recognized that indexedDB access is only available to one connection at a time and in a second tab with a connection open in tab 1, the IDB wont grant access anymore, which is a problem in my case.

So, I tried to fix this issue and found a thread, where a user suggested to only build the IDB connection, when it is needed. 
So, whenever I need data from IDB, I would like to open a connection, get all the data and close the connection afterwards, so a potential second tab can access the database, too. 

Is it possible to achieve this with your ngx-indexed-db too? I did not find a function that can interrupt or continue the connection in your service. 

Thanks in regard 

Jonas C.

**Comment by assuncaocharles** [comment]
I am not sure if I follow, can you provide a example from native Idexeddb of what you want to achieve with this lib?

**Comment by JonasC97** [comment]
Here is the original discussion that I am refering to: 
https://stackoverflow.com/questions/51615658/using-indexeddb-operation-in-multiple-tabs

In a nutshell: IndexedDB can only leave one active connection. A second tab is stalled until the connection in first tab is closed.
With native IndexedDB the solution would be to 
1) React on a onblocked Event, so the user can be warned (I did not find that in your implementation either)
2) Create a mechanism to open a connection only temporarily.

Here is the example that you can find in the thread too, but I prefer the link because of format reasons.

function open(name, version, callback) {
  var request = indexedDB.open(name, version);
  request.onsuccess = function(event) {
    var db = request.result;
    callback(result, null);
  };
  request.onerror = function(event) {
    console.log('Failed to connect');
    callback(null, 'error');
  };
  request.onblocked = function(event) {
    console.log('Failed to connect because blocked');
    callback(null, 'blocked');
  };
}


open('foo', 1, function onopen(db, error) {
  if(error === 'error') {
    console.log('cannot do stuff because of error');
  } else if(error === 'blocked') {
    console.log('cannot do stuff because blocked');
  } else {
    console.log('do stuff with db', db.name);

    // do db operation here

    // cleanup when done
    db.close();
  }
});
