### ISSUE TITLE
DB-Access prior to subscription

### ISSUE THREAD

**Issue by lmogwitz** [assuncaocharles/ngx-indexed-db#267]
I recently migrated my App from v5 (Promise-based) to v9.1.2(Observable-based) and refactored all my Observable-Wrappers.
If you now create an Observable without subscription:

`const request$ = this.indexedDBService.getAll('DOES_NOT_EXIST');`

indexedDBService queries the db and throws an error even though it was not subscribed to.

I would have expected it to work the same way angular's httpClient works when you create an Observable without subscription:

`const request$ = this.httpClient.get('DOES_NOT_EXIST);`

works fine.

The way I wrapped the Promises prior to upgrading to V9 was done like that:

``` 
const getAllWrapper$ = <T>(storeName: string): Observable<T[]> => {
    return new Observable<T[]>((observer) => {
        this.indexedDBService.getAll<T>(storeName).then(
            (dbResult: T[]) => {
                observer.next(dbResult);
                observer.complete();
            }, (error) => {
                observer.error(error);
            }
        );
    });
};
```
which only queried the db when subscribing to it.

Background:
I am using Request-classes to retrieve data depending on the user's online/offline state.
These classes have 2 properties: `onlineRequest$` and `offlineRequest$`.
`onlineRequest$` usually is an observable calling httpClient.
`offlineRequest$` is an observable calling indexedDbService.

In some cases I extends some SuperClass to create the observables but I set the storeName as property in the subclass.
Now I get indexedDbErrors when creating both Observables in the superclass' constructor because the storeName is not known while creating the Observable.

Here's an example:

```
export abstract class BaseSomeRequest<T> {
    protected abstract storeName: string;
    
    private readonly _onlineRequest$: Observable<T[]>;
    private readonly _offlineRequest$: Observable<T[]>;
    
    protected constructor(httpClient: HttpClient, private indexedDBService: NgxIndexedDBService) {        
        this._onlineRequest$ = httpClient.get<T[]>('validUrl');
        this._offlineRequest$ = this.getAllOffline$();
    }
    
    public get onlineRequest$(): Observable<T[]> {
        return this._onlineRequest$;
    }
    
    public get offlineRequest$(): Observable<T[]> {
        return this._offlineRequest$;
    }
    
    private getAllOffline$(): Observable<T[]> {
        return this.indexedDBService.getAll(this.storeName);
    }
}

export class SomeRequest extends BaseSomeRequest<any> {
    protected storeName = 'EXISTING_STORE';
    
    public constructor(httpClient: HttpClient, indexedDBService: NgxIndexedDBService) {
        super(httpClient, indexedDBService);
    }
}
```

As soon as I create an instance of SomeRequest I get an error 'objectstore does not exists: undefined' - This is because the db is queried prior to subscription and this.storeName is not available in the superclass' constructor.

**Comment by assuncaocharles** [comment]
Hey, I think it's a reasonable request. 

Fixed in #271 Version 9.2.0
