### ISSUE TITLE
Failed to execute 'add' on 'IDBObjectStore'

### ISSUE THREAD

**Issue by emseider** [assuncaocharles/ngx-indexed-db#272]
I'm trying to add the key of the entry with add and addBulk methods.
this.db.add(storeName, { closeTime:  232312312 }, {id: 232312312 } );

Now here is the error:
Failed to execute 'add' on 'IDBObjectStore': The object store uses in-line keys and the key parameter was provided.

I set autoIncrement to false but still happens
storeConfig: { keyPath: 'id', autoIncrement: false },

**Comment by assuncaocharles** [comment]
Can you reproduce in a codesandbox? I just tested it and it's working.

**Comment by emseider** [comment]
There you go man!
https://codesandbox.io/embed/confident-bash-kzs9j?fontsize=14&hidenavigation=1&theme=dark

**Comment by assuncaocharles** [comment]
You are basically using it wrong. The correct usage: https://codesandbox.io/s/suspicious-curie-m3x5d?file=/src/app/app.component.ts:364-534

**Comment by mapurba** [comment]
> You are basically using it wrong. The correct usage: https://codesandbox.io/s/suspicious-curie-m3x5d?file=/src/app/app.component.ts:364-534

can you please recreate this sandbox as i am facing the exactly same issue
