### ISSUE TITLE
updateByKey produces error message

### ISSUE THREAD

**Issue by tunger** [assuncaocharles/ngx-indexed-db#281]
When using `updateByKey`, the record gets updated, but produces an error message in the subsequent `objectStore.get` call.

```
ERROR DOMException: Failed to execute 'get' on 'IDBObjectStore': The transaction has finished.
    at IDBTransaction.transaction.oncomplete [as __zone_symbol__ON_PROPERTYcomplete] 
    at IDBTransaction.wrapFn
    at ZoneDelegate.invokeTask
    at Object.onInvokeTask
    at ZoneDelegate.invokeTask
    at Zone.runTask
    at ZoneTask.invokeTask [as invoke]
    at invokeTask
    at IDBTransaction.globalZoneAwareCallback
```

That's this line: https://github.com/assuncaocharles/ngx-indexed-db/blob/16959db54c53f458547fffa311873d18672f0c21/projects/ngx-indexed-db/src/lib/ngx-indexed-db.service.ts#L308

Probably needs a new transaction for the query?

**Comment by aparzi** [comment]
Hi @tunger,
this problem will be investigated as soon as possible.

**Comment by aparzi** [comment]
Hi @assuncaocharles,
this issue should be closed.

Thanks.
