### ISSUE TITLE
Angular 13 | Cannot find name 'IDBArrayKey'

### ISSUE THREAD

**Issue by Pascalmh** [assuncaocharles/ngx-indexed-db#285]
After upgrading to Angular 13 I receive the following error when I try to build/serve my application

```bash
Error: node_modules/ngx-indexed-db/lib/ngx-indexed-db.meta.d.ts:41:84 - error TS2304: Cannot find name 'IDBArrayKey'.

export declare type Key = string | number | Date | ArrayBufferView | ArrayBuffer | IDBArrayKey | IDBKeyRange;
```

These are the dependencies I am using:

```json
"@angular/*": "13.*.*",
// …
"ngx-indexed-db": "9.4.0",
// …
"typescript": "4.4.4",
```

**Comment by mawtrack** [comment]
The definitions of these types are lost somewhere.

**Comment by aprilmay** [comment]
Maybe: just replace IDBArrayKey by IDBValidKey

**Comment by rfldn** [comment]
Works fine with @aprilmay's answer, should we propose a PR?

**Comment by aparzi** [comment]
HI @rfldn,
yes I think a PR should be open. In general, we should also give support for angular 13.

**Comment by rfldn** [comment]
thanks @Pascalmh you were faster 👍

**Comment by rfldn** [comment]
Hello @assuncaocharles how is it going? Any plan to merge this soon? 🙏
