### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by aparzi** [assuncaocharles/ngx-indexed-db#287]
Hi @assuncaocharles,
Should we implement support for Angular 13, what do you think?

**Comment by alfmos** [comment]
Actually, I updated to angular 13. There was a single error on
```
export declare type Key = string | number | Date | ArrayBufferView | ArrayBuffer |IDBArrayKey |  IDBKeyRange; 
```
inside ngx-indexed-db.meta.d.ts (line 41)

IDBArrayKey doesn't exists anymore (or maybe something else, I couldn't go deeper).

Commenting the key as made the module working.
```
export declare type Key = string | number | Date | ArrayBufferView | ArrayBuffer  |  IDBKeyRange; //|IDBArrayKey
```
I don't know if it's useful or not. For me, it worked

**Comment by aparzi** [comment]
Hi @alfmos,
have you updated ngx-indexed-db with angular version 13? Because I don't see PR related to this

**Comment by alfmos** [comment]
Hi @aparzi 
there was this one:
#285 
that gives a correct solution.
I don't know if it's been merged

**Comment by assuncaocharles** [comment]
It's merged

**Comment by alfmos** [comment]
thanks, I'm going to update

**Comment by rfldn** [comment]
thanks @assuncaocharles 🙏
