### ISSUE TITLE
returned type is wrong in some methods

### ISSUE THREAD

**Issue by vahid18u** [assuncaocharles/ngx-indexed-db#289]
this is the signature for adding new entry in the store:
add<T>(storeName: string, value: T, key?: any): Observable<T>;

I guess the returned type should be the following since it returns 'id' too: 
add<T>(storeName: string, value: T, key?: any): Observable<T & {id: number}>;

**Comment by HamzaMoiyadi** [comment]
Can we submit a pull request to fix this?

**Comment by aparzi** [comment]
Hi @vahid18u and @HamzaMoiyadi,
do you want me to take care of it?

**Comment by HamzaMoiyadi** [comment]
@aparzi please do :D

**Comment by aparzi** [comment]
@HamzaMoiyadi 
in the next few days I will try to release the change.

**Comment by vahid18u** [comment]
@aparzi thank you so much.

**Comment by aparzi** [comment]
Hi @vahid18u, @vahid18u,
are you referring to the method signature specified in the readme? Because in the code it seems correct to me, at most I will ask @assuncaocharles to republish the readme.
I just wanted to clarify that the add method returns the newly added entity so it will return the generic type T.

**Comment by HamzaMoiyadi** [comment]
> this is the signature for adding new entry in the store: add(storeName: string, value: T, key?: any): Observable;
> 
> I guess the returned type should be the following since it returns 'id' too: add(storeName: string, value: T, key?: any): Observable<T & {id: number}>;

This is the data type that is returned from the `.add` method, and this is how I'm handling the errant type right now.

```
 this._indexedDb
      .add("..." {
        filename,
        blob,
        id
      })
      .subscribe((response: any) => {
        // Change the ID to Random Number
        this.service.id =
          response["id"];
          ...
```

**Comment by aparzi** [comment]
@HamzaMoiyadi,
thanks, now it's clear to me. I have already done a PR that is going to solve this problem of yours.
