### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by pelord** [assuncaocharles/ngx-indexed-db#290]
Is it possible to build a changelog on new releases? Sort of documentation for new feature/ breaking changes? Thanks!

**Comment by assuncaocharles** [comment]
@pelord feel free to open a PR :)

**Comment by pelord** [comment]
haa :) ok! i will try!

**Comment by FazCodeFR** [comment]
+1

**Comment by assuncaocharles** [comment]
We could use semantic release here. @gabriel949 Wanna pick this one?

**Comment by FazCodeFR** [comment]
You can use 
https://github.com/googleapis/release-please (https://www.conventionalcommits.org/en/v1.0.0/ | https://semver.org/ )
