### ISSUE TITLE
Out-of-line key config

### ISSUE THREAD

**Issue by andreaslarssen** [assuncaocharles/ngx-indexed-db#293]
Is this possible? Sorry if it's just me not understanding the documentation

**Comment by assuncaocharles** [comment]
I have no idea what this is supposed to mean, can you describe it better?

**Comment by andreaslarssen** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Terminology#key

`Every object store must have a name that is unique within its database. The object store can optionally have a key generator and a key path. If the object store has a key path, it is using in-line keys; otherwise, it is using out-of-line keys.`

**Comment by andreaslarssen** [comment]
Maybe I just understand don't the docs, but this is my config:

```
objectStoresMeta: [{
  store: 'store-name',
  storeConfig: {
    keyPath: 'id',
    autoIncrement: false
  }
}]
```
When I use the updateByKey method, and pass in the key, I get the error `The object store uses in-line keys and the key parameter was provided.` I'm not sure what (in my config) that makes me use in-line-keys as opposed to out-of-line keys. Is it the autoincrement: false option?

**Comment by assuncaocharles** [comment]
You are doing that when you declare the keyPath, can you create a sandbox reproducing the error?

**Comment by andreaslarssen** [comment]
Sorry, it's too much work. 

But with the config above, and calling this method:

```
this.dbService.addItem('store-name', {data: 'test', id: 1},  1).
```

I get the error: `The object store uses in-line keys and the key parameter was provided.`

I see now that the addItem method is not documented. Am I not supposed to use it? Should I use the add method instead?

**Comment by assuncaocharles** [comment]
Sorry I will not be able to help you if you are not willing to repro it in a codesandbox
