### ISSUE TITLE
On the struggle Bus

### ISSUE THREAD

**Issue by wmbutler** [assuncaocharles/ngx-indexed-db#30]
I've been able to create a database and create an object store, but I can't seem to add an entry. Here is my code:

```
  saveMovie(payload: object) {
    console.log(payload);
    const db = new NgxIndexedDB('mobileRecall', 1);
    db.openDatabase(1, evt => {
      const objectStore = evt.currentTarget.result.createObjectStore('movies', { keyPath: 'id', autoIncrement: true })
      .then(db.add('movies', payload).then(() => evt('success'), (err) => console.log(err)));
    });
```

Payload is this object

```
{
  Poster: "https://m.media-amazon.com/images/M/MV5BNDY3NzQ0NjYxM15BMl5BanBnXkFtZTcwMDkzODM2Mw@@._V1_SX300.jpg"
Title: "The Sorcerer's Apprentice"
Type: "movie"
Year: "2010"
imdbID: "tt0963966"
}
```

Here are the entities being created

![screen shot 2019-02-10 at 2 28 40 pm](https://user-images.githubusercontent.com/1254810/52539134-38772500-2d40-11e9-9a86-ea6167d4ba34.png)

Hoping someone out there can put together a fully working sample. I'd be ahppy to contribute it back to the readme here.

**Comment by assuncaocharles** [comment]
HI @wmbutler ,

Here is a working example with your use case:

https://stackblitz.com/edit/angular-wsxsnw

**Comment by wmbutler** [comment]
You are awesome!!

**Comment by wmbutler** [comment]
I have it working now from a button, but I need to call an operation after my page loads. When calling from ngInit(), it complains:

```
You need to use the openDatabase function to create a database before you query it!
```

Is there a better place to call it from when the route loads?

https://stackblitz.com/edit/angular-vjxfzk

**Comment by assuncaocharles** [comment]
It's difficult to determine what is best for you or your problem specific. What you can do maybe is us it in the resolve of the openDatabase as I last changed in the stackblitz repo.  

https://stackblitz.com/edit/angular-s5nyfz
