### ISSUE TITLE
Angular 14

### ISSUE THREAD

**Issue by aparzi** [assuncaocharles/ngx-indexed-db#323]
Hello everyone, 
support for angular 14 should be foreseen.

**Comment by andreaslarssen** [comment]
Any updates on supporting newer versions of Angular?

**Comment by aparzi** [comment]
Hi @andreaslarssen,
hello, I'll try to work on it these days, if so write me back.

**Comment by aparzi** [comment]
@andreaslarssen now support Angular 14 💪💪🥳🥳🥳🥳
