### ISSUE TITLE
ngx-indexed-db version 11.0.2, cannot make it work with Angular 11

### ISSUE THREAD

**Issue by tedKarabeliov** [assuncaocharles/ngx-indexed-db#327]
Hello,

I'm trying to upgrade ngx-indexed-db version in my project from 9.4.2 to 11.0.2 but I am getting errors.
I'm currently using Angular 11. I tried with Angular 14 and it works fine.

Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

static ɵfac: i0.ɵɵFactoryDeclaration<NgxIndexedDBService, never>;
Error: node_modules/ngx-indexed-db/lib/ngx-indexed-db.service.d.ts:144:22 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

static ɵprov: i0.ɵɵInjectableDeclaration<NgxIndexedDBService>;
Error: node_modules/ngx-indexed-db/lib/ngxindexeddb.module.d.ts:7:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

static ɵfac: i0.ɵɵFactoryDeclaration<NgxIndexedDBModule, never>;
Error: node_modules/ngx-indexed-db/lib/ngxindexeddb.module.d.ts:8:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

static ɵmod: i0.ɵɵNgModuleDeclaration<NgxIndexedDBModule, never, [typeof i1.CommonModule], never>;
Error: node_modules/ngx-indexed-db/lib/ngxindexeddb.module.d.ts:9:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

static ɵinj: i0.ɵɵInjectorDeclaration<NgxIndexedDBModule>;

Is it expected not to work with Angular 11?

**Comment by assuncaocharles** [comment]
Hi @tedKarabeliov 

I think the current version is not supporting NG 11, so you will probably have to use some older versions, since we are trying to keep up with angular breaking changes.

**Comment by tedKarabeliov** [comment]
Hi @assuncaocharles 

Thank you for your quick response :) I will keep this in mind then.
