### ISSUE TITLE
Unable to delete database because it's blocked

### ISSUE THREAD

**Issue by EmadR** [assuncaocharles/ngx-indexed-db#363]
when i call 
this.dbService.deleteDatabase().subscribe((deleted) => {
  console.log('Database deleted successfully: ', deleted);
});

log in console: 
ERROR Error: Unable to delete database because it's blocked
    at deleteDBRequest.onblocked [as __zone_symbol__ON_PROPERTYblocked] (ngx-indexed-db.mjs:531:27)

**Comment by aparzi** [comment]
Hi @EmadR,
most likely there is an open connection to that database somewhere.

**Comment by EmadR** [comment]
hi @aparzi 
how to close all connections?

**Comment by aparzi** [comment]
You generally never need to close a connection. Except if You may wish to explicitly close a connection if you anticipate upgrading your database schema. Here's the scenario:

1) A user opens your site in one tab, and leaves it open.

2) You push an update to your site, which includes code to upgrade the database schema, increasing the version number.

3) The same user opens a second tab to your site and it attempts to connect to the database.

What situation do you have?

**Comment by EmadR** [comment]
I have a panel, when the user logs in, I get information from server and save it in the form of a table in indexeddb. Now, when the same user wants to exit the panel, I delete the database and it gives the error I said

**Comment by aparzi** [comment]
how do you save the information in the database?

**Comment by EmadR** [comment]
const dbConfig: DBConfig  = {
  name: 'MyDb',
  version: 1,
  objectStoresMeta: [{
    store: 'employee',
    storeConfig: { keyPath: 'id', autoIncrement: true },
    storeSchema: []
  }]
};

this.dbService
  .add('employee', response.data)
  .subscribe((key) => {
    console.log('key: ', key);
  });

**Comment by aparzi** [comment]
Okay, I will investigate the issue.

**Comment by aparzi** [comment]
Hi @EmadR,
why your storeSchema is empty array? can you add your store schema?

Example:
storeSchema: [
        { name: 'name', keypath: 'name', options: { unique: false } },
        { name: 'email', keypath: 'email', options: { unique: false } },
      ]

**Comment by aparzi** [comment]
HI @EmadR,
any news?

**Comment by EmadR** [comment]
Must it be set?
Because for the update, the response I get may not match the configuration and the keys may be different

**Comment by aparzi** [comment]
What do you mean update?

**Comment by EmadR** [comment]
I may receive new data from the server and have to update my table. This is what I mean by update.

**Comment by aparzi** [comment]
Hi @EmadR, did you solve the problem?

**Comment by EmadR** [comment]
hi @aparzi , no

**Comment by JonataB** [comment]
I am trying to fix this

**Comment by aparzi** [comment]
Hi @EmadR,
in 19.3.0 the problem should have been solved. I'm closing the issue if the problem persists you can reopen it.
