### ISSUE TITLE
Support for "out-of-line" keys?

### ISSUE THREAD

**Issue by BruceWilcox** [assuncaocharles/ngx-indexed-db#365]
Do you support "out-of-line" keys? 

If so, can you give an example of how to set the 'storeConfig' value and 'storeSchema' values?

My data already has an unique "id" field.

I am getting error: DOMException: Failed to execute 'add' on 'IDBObjectStore': The object store uses in-line keys and the key parameter was provided.

Thank you.

**Comment by aparzi** [comment]
Hi @BruceWilcox,
Can you share your storeConfig and a single data that you want a store? It seems to me that out-line-key not supported.

Thansk.

**Comment by aparzi** [comment]
Hi @BruceWilcox,
if you already id for your entities should be configure your store in this mode:
<img width="792" alt="Screenshot 2023-10-23 alle 12 53 27" src="https://github.com/assuncaocharles/ngx-indexed-db/assets/16490359/bbd9f6d3-6f35-45cc-a425-b4dfdcda1373">

Set id or your custom key for **storeConfig** with autoincrement false, and call method add, put and etc... without passing key.

**Comment by BruceWilcox** [comment]
Please see my project at https://github.com/iTipsDev/demo-angular-ngx-indexed-db

It works ok if records added one at a time.  But fails when using bulk option. I need the better performance of the bulk option.

![error](https://github.com/assuncaocharles/ngx-indexed-db/assets/9534661/3a961e89-c158-4c12-ad2e-cd516173e3da)

**Comment by aparzi** [comment]
Hi @BruceWilcox,
I tried your example but bulkAdd works fine for me. Are you sure your db is empty? Because if you do the normal add first and then the bulkAdd this won't work

**Comment by BruceWilcox** [comment]
I am still trying to get the same results are you are.  Is "if you do the normal add first and then the bulkAdd this won't work" a documented limitation?

**Comment by aparzi** [comment]
If you call the add method you wrote, it iteratively inserts each element of your json. BulkAdd does the same thing in a massive way, consequently if the db is not empty you are trying to insert duplicate elements (since you are working with the id of each element of the same json).
