### ISSUE TITLE
What is the current Version?

### ISSUE THREAD

**Issue by felix-krause** [assuncaocharles/ngx-indexed-db#371]
NPM says there is a version 16.0.0 but here it says 11.0.2
https://www.npmjs.com/package/ngx-indexed-db
both repos are owned by @assuncaocharles

**Comment by aparzi** [comment]
Hi @efkah,
the latest version is 16.0.0 and support Angular 16. It is recommended to follow the version indicated on npm.

If I answered your question you can ask the issue,
thanks
