### ISSUE TITLE
 Property 'continue' does not exist on type 'IDBDatabase'.

### ISSUE THREAD

**Issue by Skycader** [assuncaocharles/ngx-indexed-db#372]
This exact piece of code from documentation throws an error in Angular 17, please fix.

`    this.dbService
      .openCursor('people', IDBKeyRange.bound('A', 'F'))
      .subscribe((evt) => {
        var cursor = (evt.target as IDBOpenDBRequest).result;
        if (cursor) {
          console.log(cursor.value);
          cursor.continue();
        } else {
          console.log('Entries all displayed.');
        }
      });`
      
      Error:
      
      ✘ [ERROR] TS2339: Property 'value' does not exist on type 'IDBDatabase'. [plugin angular-compiler]

    src/app/app.component.ts:31:29:
      31 │           console.log(cursor.value);
         ╵                              ~~~~~

✘ [ERROR] TS2339: Property 'continue' does not exist on type 'IDBDatabase'. [plugin angular-compiler]

    src/app/app.component.ts:32:17:
      32 │           cursor.continue();
         ╵                  ~~~~~~~~

Application bundle generation failed. [0.063 seconds]

**Comment by aparzi** [comment]
Issue close with PR #413
