### ISSUE TITLE
Support for Angular 17

### ISSUE THREAD

**Issue by magnus-lundberg-discovery** [assuncaocharles/ngx-indexed-db#384]
If I try to run this on an Angular 17 project I get:

```
./node_modules/ngx-indexed-db/node_modules/@angular/common/fesm2022/common.mjs:6833:13-55 - Error: export 'ɵɵInputFlags' (imported as 'i0') was not found in '@angular/core' 
```

Do you have any plans to add support for Angular 17?

**Comment by aparzi** [comment]
Hi @magnus-lundberg-discovery,
as soon as possible, perhaps this week or in the next 10 days, support for Angulsr 17 will be integrated.

**Comment by magnus-lundberg-discovery** [comment]
Wonderful news. Thank you!

**Comment by aparzi** [comment]
Hi @magnus-lundberg-discovery,
publish new version (18.0.0), now support Angular 17.
