### ISSUE TITLE
Getting Uncaught (in promise): Event: {"isTrusted":true} error after upgrading to v18.0.0

### ISSUE THREAD

**Issue by Rig-ved** [assuncaocharles/ngx-indexed-db#389]
Hi Team ,

I am getting the below error everytime on my angular application after upgrading to v18.0.0 

```
Error: Uncaught (in promise): Event: {"isTrusted":true}
    at te (pxf_polyfills.js:1:15947)
    at pxf_polyfills.js:1:15028
    at pxf_polyfills.js:1:15136
    at O.invoke (pxf_polyfills.js:1:6443)
    at B.run (pxf_polyfills.js:1:1851)
    at https://cdn.finovera.com/pxf-blocks/v6.1/pxf_polyfills.js:1:16745

```

Below is my DBConfig 

```

import { DBConfig } from 'ngx-indexed-db';
export const PXFIndexedDBConfig: DBConfig = {
  name: 'pxf-indexed-db',
  version: 1,
  objectStoresMeta: [
    {
      store: 'searchPayeesReqTable',
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [],
    },
    {
      store: 'searchEbillsReqTable',
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [],
    },
    {
      store: 'searchScheduledPayments',
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [],
    },
    {
      store: 'searchProcessedPayments',
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [],
    },
    {
      store: 'searchForecastedPayments',
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [],
    },
    {
      store: 'getPaymentOptions',
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [],
    },
    {
      store: 'getForecastedPaymentDates',
      storeConfig: { keyPath: 'id', autoIncrement: true },
      storeSchema: [],
    },
  ],
};
```

P.S: This was working fine till the version 16.0.0 ? Is there any way to address the same . What i have observed is that there is always a version mismatch within the indexed DB when the application loads even though i have set the value to "1" inside DBConfig

**Comment by aparzi** [comment]
Hi @Rig-ved,
can you try in private browsing?

**Comment by Rig-ved** [comment]
Hi @aparzi 

With private browsing/ incognito mode  it always works since the version at the time of load is always set to 1 which is congruent to my dbconfig version and hence there is no mismatch onto the same, resulting in no error at the console  .

The issue is persistent everytime when the application is loaded in a normal view / web view. Can you please help me on the same

**Comment by aparzi** [comment]
Hi @Rig-ved,
I will certainly try to help you in my free time.  What version do you currently have in your local db?  Obviously destroying the db and recreating it cannot be a solution right?

**Comment by Rig-ved** [comment]
Hi @aparzi 

The issue was **never existent** on the ngx-indexed-db version **16.0.0**. I recently migrated to the latest version **18.0.0** and there i am continuously getting the above issue in a normal viewing mode. Destroying the DB wont be a solution , as I am saving few data from ngxs state to there .

**Comment by aparzi** [comment]
Hi @Rig-ved,
so you started with version 16 right? Was upgrading to version 18 your first upgrade? These days I will try to make a local sandbox to simulate the case

**Comment by Rig-ved** [comment]
Hi @aparzi 

Yes i started with **16.0.0 last year** september .Then i upgraded to **18.0.0** just a few days back in which i started encountering the issue . I downgraded again the version to **17.1.0** to verify if the issue exists in that version or not and yes i was able to replicate the same even there . So thats pretty much what i did

**Comment by aparzi** [comment]
What version of Angular are you using?

**Comment by Rig-ved** [comment]
Currently i am using `@angular: "17.3.7"`. But even with angular 17.3.7 when i had the ngx-indexed-db version of **16.0.0** it was working fine

**Comment by aparzi** [comment]
Hi @Rig-ved,
I did a couple of tests locally by installing version 16 of the library with Angular 17.3, bringing the indexeddb version up to 11. I subsequently updated the library to version 18.0.0 but everything seems to continue to work correctly. Could you add some more details to replicate the error. For example, what operation do you call to get the error out? does even a simple get give you this error?
Only this warning that can be ignored
![image](https://github.com/assuncaocharles/ngx-indexed-db/assets/16490359/2634463b-d03a-417d-a5c2-80af5c37d35c)

**Comment by Rig-ved** [comment]
hi @aparzi  

Thats very very strange !! Would it be possible for you to share your DB config details ? And can you check is your files bundled while running the local app ? For me the error pops in the console at the time of application page load itself

**Comment by aparzi** [comment]
Hi @Rig-ved,
in the next few days I will try to share my project with you.  When the page loads, do you make any particular library calls?

**Comment by Rig-ved** [comment]
@aparzi 

Sure you can share the project . Library calls I don't make . What i do though is  few css stylesheet calls from CDN and few REST api calls to fetch data

**Comment by aparzi** [comment]
Hi @Rig-ved,
at this point I suspect that the error lies with this library. Do you have third party services included in the project?

**Comment by aparzi** [comment]
Hi @Rig-ved,
If you no longer encounter the problem you can also close the issue, otherwise let us know.
Thank you

**Comment by Rig-ved** [comment]
Hi @aparzi 

Sorry for the late response , I did post a comment couple of hours back but somehow i am not seeing the same.

Anyways, When you say error lies with the library , which library you refer to ? Is it ngx-indexed-db ? Moreover , I have only couple third party libraries, one for state manangement [NGXS](https://www.ngxs.io/) and one for translate service [ngx-translate](https://github.com/ngx-translate/core) and thats pretty much it. I am encountering the problem still

**Comment by aparzi** [comment]
It's very strange.
Can you create a small reproduction repo or codesandbox @Rig-ved ?

**Comment by Rig-ved** [comment]
Hi @aparzi 

Can you answer to my previous question ? U said error lies with the library ? Which library you are talking about ?

**Comment by aparzi** [comment]
I said that badly. I meant that the error could be in some other library? Can you replicate this in a sandbox?

**Comment by Rig-ved** [comment]
Hi @aparzi 

I will try to replicate the same in sandbox and keep you updated

**Comment by aparzi** [comment]
@Rig-ved thanks.

**Comment by aparzi** [comment]
Hi @assuncaocharles,
can you close this issue? The problem could not be reproduced
