### ISSUE TITLE
Support Angular v18

### ISSUE THREAD

**Issue by danipavic** [assuncaocharles/ngx-indexed-db#393]
**Description**
As the title says, please add support for Angular v18.

**Comment by aparzi** [comment]
Hi @danipavic,
we will try to do it as soon as possible.

Thanks for your feedback.

**Comment by aparzi** [comment]
Hi @danipavic,
I have open a PR for to support Angular 18. #394

**Comment by aparzi** [comment]
Hi @danipavic, support for Angular 18 is now available.

if everything is ok you can close the issue.  Thank you

**Comment by danipavic** [comment]
Thanks!
