### ISSUE TITLE
ERROR ReadOnlyError: Failed to execute 'update' on 'IDBCursor'

### ISSUE THREAD

**Issue by bartuck** [assuncaocharles/ngx-indexed-db#399]
When you use the "openCursor" method and then perform the "update" method on the found cursor, the following error occurs:

`ReadOnlyError: Failed to execute 'update' on 'IDBCursor': The record may not be updated inside a read-only transaction`

for "ngx-indexed-db": "^19.0.0".

The "openCursor" method should have possibility to set "mode" of transaction as "readwrite", according to the docs https://developer.mozilla.org/en-US/docs/Web/API/IDBCursor/update

Thanks!

**Comment by aparzi** [comment]
Hi @bartuck, can you share the code or stackblitz?

Thanks.

**Comment by bartuck** [comment]
@aparzi I have reproduced the error here https://stackblitz.com/edit/angular-p8kzfu?file=src%2Fmain.ts

**Comment by aparzi** [comment]
@bartuck thanks, I will look into the problem as soon as possible.

**Comment by aparzi** [comment]
Hi @bartuck,
I have published new version 19.0.1, it should work now, let me know.

Thanks.

**Comment by bartuck** [comment]
@aparzi Ok, now it seems to work correctly. Thanks for your quick update! 💪
