### ISSUE TITLE
Need provideNgxIndexedDB to use at ApplicationConfig in Angular 18 where ngModule is not used. 

### ISSUE THREAD

**Issue by VTrendZLabs** [assuncaocharles/ngx-indexed-db#400]
Using a temporary fix as below. 

export const appConfig: ApplicationConfig = {
  providers: [
    NgxIndexedDBService,
    { provide: CONFIG_TOKEN, useValue: { [dbConfig.name]: dbConfig } },
  ],
};

**Comment by aparzi** [comment]
Hi @VTrendZLabs,
can you share an example or stackblitz? are you using only standalone components?

Thanks

**Comment by MRinaldi9** [comment]
if not a problem i can pick this issue and make a PR about it

**Comment by aparzi** [comment]
Hi @MRinaldi9,
go ahead and thanks for the support.

**Comment by aparzi** [comment]
[@all-contributors](https://github.com/all-contributors) please add [MRinaldi9](https://github.com/MRinaldi9) for code

**Comment by MRinaldi9** [comment]
this issue can be closed as completed with the introduction of the new api `provideIndexedDb` @aparzi

**Comment by aparzi** [comment]
Thanks @MRinaldi9
