### ISSUE TITLE
Remove the console.logs

### ISSUE THREAD

**Issue by fedeverdi** [assuncaocharles/ngx-indexed-db#428]
I looked in the node_modules and there doesn't seem to be a way to avoid the console.logs.. can you confirm this? Possibly a flag in the DbConfig?

I'm talking about 'Database connection closed:'

**Comment by aparzi** [comment]
Hi @fedeverdi,
I will remove the log in the next version, I will release it asap.

Thanks

**Comment by aparzi** [comment]
Hi @fedeverdi,
I release new version 19.3.1 that remove console.logs.

**Comment by fedeverdi** [comment]
Thx @aparzi
