### ISSUE TITLE
Unable to delete database

### ISSUE THREAD

**Issue by appu-sm** [assuncaocharles/ngx-indexed-db#45]
Hi, there is no option to delete a database, even updating the db version didn't get rid of the old database.

**Comment by suleodu** [comment]
same here

**Comment by assuncaocharles** [comment]
I will try to check this as soon as possible, meanwhile.. PR's are welcomed! :D

**Comment by assuncaocharles** [comment]
deleteDatabase() method added in the latest version ( 2.0.7 )
