### ISSUE TITLE
Upgrade to Angular 8 Fails

### ISSUE THREAD

**Issue by jbloem9** [assuncaocharles/ngx-indexed-db#55]
I am trying to upgrade my project to angular 8 but am getting the following error;

![Angular8Upgrade](https://user-images.githubusercontent.com/7578265/58995987-7c8bb980-884a-11e9-89d4-b077d0aebf43.PNG)

Will this package be upgraded to work with Angular 8?

**Comment by assuncaocharles** [comment]
Hi,

I will be looking at it. But PRs are always welcome. :)

**Comment by assuncaocharles** [comment]
It's fixed on version @2.1.0. Can you check it please?
