### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by WEBhicham** [assuncaocharles/ngx-indexed-db#65]
Hello there. would it be possible to have a example of an migration to a newer version in the readme?

**Comment by assuncaocharles** [comment]
Hi @WEBhicham 

You mean to update your own indexed-db to a new version of?

**Comment by EndarValuk** [comment]
Hi @assuncaocharles!
yep, that would be nice. As for now it not clear, how to update already created indexed-db to newer version..

**Comment by assuncaocharles** [comment]
Alright, that makes sense...

I'm currently working in the version 3 where you will be able to inject the DB service using DI. I will be looking to implement the migration feature in the next version, also... PR's are always welcome 😄

**Comment by assuncaocharles** [comment]
Solved on pr #101
