### ISSUE TITLE
obtaining the id of the added entry when using autoIncrement

### ISSUE THREAD

**Issue by feline87** [assuncaocharles/ngx-indexed-db#73]
how to obtain the id of the recently added object from the database? Is the feature implemented?

**Comment by assuncaocharles** [comment]
Hi @feline87,

There's no such feature, I would recommend you to track and control the id's outside.

**Comment by assuncaocharles** [comment]
Hi @feline87 ,

Just published the new version which supports this feature. You can do it as in the following code:

```
this.db.add('people', { name: 'name', email: 'email' }).then(
      (evt) => {
        console.log('Id: ', evt.target.result)
      },
      error => {
        console.log(error);
      }
    );
  }
```

https://stackblitz.com/edit/angular-jxgm4i
