### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by EndarValuk** [assuncaocharles/ngx-indexed-db#76]
Not working with ie11.
Falling in error, and not resolving data from storage.

Im on mobile, when touch my pc, add more info.
Tx for understanding

**Comment by assuncaocharles** [comment]
Hi @EndarValuk ,

Please, post more details when you can.

**Comment by MattBorkowski** [comment]
I took a look into this issue and it seems like with version 2.2.5 on the update function we are using an optional parameter for the key but aren't safe checking the objectStore.put function if that key is undefined. Simply removing the key param allows the update operations to work for IE and Edge.

![Screen Shot 2019-12-20 at 10 06 14 AM](https://user-images.githubusercontent.com/21329634/71267563-84a3d600-2310-11ea-946c-e7e47aeaa653.png)

I propose we add a simple if statement to the put to keep support for IE and edge

```
if(key){
 objectStore.put(value, key);
} else {
objectStore.put(value);
}
```

**Comment by assuncaocharles** [comment]
Hi @MattBorkowski 

Can you open a PR with your suggestion?

**Comment by MattBorkowski** [comment]
I sent in a PR, take a look whenever you have time. Hopefully this can help others that are running into the issue as well. Might be worth documenting these issues in a FAQ section.

**Comment by assuncaocharles** [comment]
Thanks @MattBorkowski

**Comment by assuncaocharles** [comment]
@EndarValuk can you try it on IE with the new version 3.0.13 and see if it works?
