### ISSUE TITLE
Could not find a declaration file for module 'ngx-indexed-db'

### ISSUE THREAD

**Issue by emps** [assuncaocharles/ngx-indexed-db#93]
![2019-10-18 13_35_30-local-db service ts — D__dev_projects_copa_frontends_web-app — Atom](https://user-images.githubusercontent.com/2281169/67087778-440ecb80-f1ac-11e9-8487-a2a459213612.png)

**Comment by emps** [comment]
its happening only with 2.2.5 there is .../node_modules/ngx-indexed-db/dist/ngx-indexed-db/....

making a folder mess plz fix this to be like in 2.2.4  .../node_modules/ngx-indexed-db/...

**Comment by assuncaocharles** [comment]
Hi @emps 

I will be checking this over the weekend. Thanks for reporting :)

**Comment by assuncaocharles** [comment]
Hi @emps 

It's fixed now in the versio 2.2.6

Thanks
