### ISSUE TITLE
NgxIndexedDBModule.forRoot() unusable in production build.

### ISSUE THREAD

**Issue by tgrudelj** [assuncaocharles/ngx-indexed-db#94]
Hi,

I followed the readme made available at [https://www.npmjs.com/package/ngx-indexed-db](url) and created an angular8 project that attempts to inject the NgxIndexedDBModule the way the readme suggests. I'm attaching two screenshots, one consisting of the readme I followed, and the other consisting of code that is raising errors, within app.module.ts. 

My Error:

`ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'NgxIndexedDBModule' was called.
Unexpected value 'undefined' imported by the module 'AppModule in C:/Users/REDACTED/REDACTED/REDACTED/REDACTED/REDACTED/src/app/app.module.ts'
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'NgxIndexedDBModule' was called.`

Look for a "THIS CAUSES THE ERROR" clause within the next section called "My app.module.ts".

My app.module.ts:
(you can visit [https://pastebin.com/KFgymh7f](url) if it is not very readable in this post)

//--------------------
`import { DBConfig } from 'ngx-indexed-db';
import { NgxIndexedDBModule } from 'ngx-indexed-db';
import { NgModule } from '@angular/core';

const dbConfig: DBConfig = {name: 'MyDb', version: 1, objectStoresMeta: [
{
store: 'people',
storeConfig: { keyPath: 'id', autoIncrement: true },
storeSchema: [
{ name: 'name', keypath: 'name', options: { unique: false } },
{ name: 'email', keypath: 'email', options: { unique: false } }
]
}
]};

@NgModule({
declarations: [],
imports: [
NgxIndexedDBModule.forRoot(dbConfig), //THIS CAUSES THE ERROR
],
providers: [],
})
export class AppModule {}`
//------------------

The sole instantiation of a NgxIndexedDBService itself is not even relevant - the application does not reach the point of attempting to instantiate an app.component.ts.

![ngindexeddb2](https://user-images.githubusercontent.com/50824915/67299352-d8e73100-f4ec-11e9-8cde-69d5741937bc.png)
![ngindexeddb](https://user-images.githubusercontent.com/50824915/67302363-15b52700-f4f1-11e9-8d9f-5ce86caf3658.png)

**Comment by assuncaocharles** [comment]
Hi @tgrudelj 

Problem fixed in version 3.0.4

Let me know if you face it again :)
