### ISSUE TITLE
Migration: getByKey has been removed

### ISSUE THREAD

**Issue by Wobow** [assuncaocharles/ngx-indexed-db#96]
Hi !
I was looking into this lib and noticed that the getByKey function is not available (yet?) in the NgxIndexedDBService. It was in previous versions, but since the refactor it's just gone. Even though it's still referenced in the documentation.

I get that the 3.0 is probably still in progress since there was no release yet, but I thought it was a good idea to point it out.

**Comment by assuncaocharles** [comment]
Hi @Wobow 

Yes, it will still be implemented just focusing in solve some bugs as priority for now. But thanks for point it out.

**Comment by ashokpn** [comment]
Any alternate for getByKey? getById is not working for not numeric keys, maybe that your indention I guess.  please let me know if you have any alternate already there.

**Comment by assuncaocharles** [comment]
Hi @ashokpn 

Temporally you can use `getByIndex`

**Comment by assuncaocharles** [comment]
Fixed on version 3.0.5
