### ISSUE TITLE
can a compound key be used?

### ISSUE THREAD

**Issue by arboledasaa** [assuncaocharles/ngx-indexed-db#98]
Hi,

So, the native indexed-db can use a array as keypath. Could this be added? currently it's acepting a string only, would it break anything?

Would compile and do a pull request, but haven't been able to run ng test successfully...

**Comment by assuncaocharles** [comment]
Hi @arboledasaa 

Fell free to open the PR, you can ignore the tests for now.

**Comment by assuncaocharles** [comment]
Hi @arboledasaa 

Just checked the PR, works fine. Merged.
